import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/templates/Header'
import Main from '../components/layout/Home'
import Footer from '../components/templates/Footer'
import { useRouter } from 'next/router'

export default function Home() {
  const { pathname } = useRouter()

  return (
    <div className={styles.container}>
      <Head>
        <title>RamonDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
      <Footer />
    </div>
  )
}
