import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/templates/Header'
import Section from '../components/section/Section'
import Footer from '../components/templates/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>RamonDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Section />
      <Footer />
    </div>
  )
}
